# Generated by Django 5.2.3 on 2025-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_img.jpg', upload_to='event_images/'),
        ),
    ]
