# render.yaml

services:
  - type: web
    name: event-management-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn event_management.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: event_management.settings
      - key: PYTHON_VERSION
        value: 3.11
